### ISSUE TITLE
redefinition of buildSizeInfo

### ISSUE THREAD

**Issue by Loulfy** [NVIDIAGameWorks/RTXMU#3]
Hello,
I may have missed something but I have a redefinition compile error on the buildSizeInfo variable, in VkAccelStructManager.cpp line 124 (redef of line 91). There must be a way to allow shadowed variables, but I think it would be better to fix it in the code.

Thanks in advance.

**Comment by pmorley-nv** [comment]
yep this code should have been tested but was quickly copied over from the D3D side.

**Comment by pmorley-nv** [comment]
does the below commit resolve your error?
https://github.com/NVIDIAGameWorks/RTXMU/commit/a738217bcf58e8e96e8244a62cd73ac97607415a
thank you for pointing this out :)

**Comment by Loulfy** [comment]
Thanks, that fixed the issue.

**Comment by pmorley-nv** [comment]
Are you using RTXMU with NVRHI/Donut or standalone?  Personal project or with a game company?  Thanks again.

**Comment by Loulfy** [comment]
I use it standalone for a personal project (public on my github).

**Comment by pmorley-nv** [comment]
ok thanks enjoy!
